name: "GitHub Actions demo20230422"
on:
    pull_request:
permissions:
    pull-requests: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: job-runs-when-pull-requests-created
              run: echo "job-runs-when-pull-requests-created"
              if: github.event_name == 'pull_request'


